version: '3.8'
services:
  db:
    container_name: 'postgres_rest'
    image: postgres:15-alpine
    ports:
      - 5432:5432
    networks:
      - rest_api
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data

  db-test:
    container_name: 'postgres_rest_test'
    image: postgres:15-alpine
    ports:
      - 5433:5432
    networks:
      - rest_api
    env_file:
      - .env.test

  # api:
  #   container_name: 'server'
  #   build:
  #     context: ./
  #     dockerfile: ./
  #   env_file:
  #     - .env
  #   ports:
  #     - 5555:4000
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - db
  #   command: yarn start

  #   networks:
  #     - rest_api

networks:
  rest_api:
